# Generated by Django 2.0.2 on 2018-03-11 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Koeran',
            new_name='Koreans',
        ),
    ]
